apps/urls.py
from django.urls import path, re_path
from .views import IndexView,ArticleDetailView,CategoryView,DateView
from . import views


urlpatterns = [
    path('',views.home,name='home'),
    path('index',IndexView.as_view(),name='index'),
    path('article/<int:article_id>',ArticleDetailView.as_view(),name='article'),
    path('category/<int:cate_id>',CategoryView.as_view(),name='category'),
    path('date/<int:year>/<int:month>',DateView.as_view(),name='date'),
    path('search/',views.article_search,name='search'),
    path('article/<int:article_id>/comment',views.comment_view,name='comment'),
    path('article/<int:article_id>/like',views.deal_like,name='like')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.urls')),
    path('ckeditor',include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/forms.py
from django import forms
from .models import ArticleComment

class ArticleCommentForm(forms.Form):
    body = forms.CharField(required=True,label="留言",
                              error_messages={'required':'好像空空阿，亲~','max_length':'想说的太多了，精简一些~','min_length':'再输入点内容吧'},
                              max_length=300,min_length=2,widget=forms.Textarea(attrs={'placeholder':'发表以下意见吧'}))

    user_name = forms.CharField(required=True,label="名字",
                               error_messages={'required':'好像空空阿，亲~','max_length':'有这么长的名字？？',},
                              max_length=300)
    class Meta:
        model = ArticleComment
        fields = ['body,user_name']


    def clean_body(self):
        message = self.cleaned_data['body']
        if "fuck" in message:
            raise forms.ValidationError('请文明用语')
        return message

    def clean_user_name(self):
        user_name = self.cleaned_data['user_name']
        if "admin" in user_name or "Admin" in user_name:
            raise forms.ValidationError('好像这名字不合适吧')
        return user_name

templates/article.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ article.title }}</title>
{% endblock %}

{% block style %}
    <link href='{% static 'css/praise.css' %}' rel="stylesheet">
    <style>
        body{
            background-image: url("{% static 'img/fire.jpg' %}");
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-position:center;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-md-10 col-lg-10 blog-view">
                <h3>{{ article.title }}</h3>
                <ul class="blog-info-description">
                    <li>作者：{{ article.author }}</li>
                    <li>分类：<a href="{% url 'category' article.category_id %}">{{ article.category }}</a></li>
                    <li>发表日期：{{ article.created_time|date:"Y-m-d H:n:s" }}</li>
                    <li class="art-view"><img src="{% static 'img/views.png' %}">：{{ article.views }}</li>
                </ul>
                <p class="blog-content">{{ article.content | safe }}</p>
                <div class="blog-more">
                    {% if previous_blog %}
                        <p>上一篇 :<a href="{% url 'article' previous_blog.pk %}">{{ previous_blog.title }}</a></p>
                    {% else %}
                        <p></p>
                    {% endif %}
                    {% if next_blog %}
                        <p>下一篇 :<a href="{% url 'article' next_blog.pk %}">{{ next_blog.title }}</a></p>
                    {% else %}
                        <p></p>
                    {% endif %}
                </div>
                <div style="text-align: center">喜欢就点个赞吧～</div>
                <div class="praise">
                    <span id="praise"><img src="{% static 'img/likes.png' %}" id="praise-img" /></span>
                    <span id="praise-txt">{{ article.likes }}</span>
                    <span id="add-num"><em>+1</em></span>
                </div>
                {#评论区#}
                {% include 'comment.html' %}
            </div>
        </div>
    </div>
    <p id="back-to-top">
        <a href="#top">
            <span><i class="fa fa-chevron-up" aria-hidden="true">
                <img src="{% static 'img/top.png' %}">
            </i></span>
        </a>
    </p>

<script>
	/* @author:Romey
	 * 动态点赞
	 * 此效果包含css3，部分浏览器不兼容（如：IE10以下的版本）
	*/
	$(function(){
		$("#praise").click(function(){
			var praise_img = $("#praise-img");
			var text_box = $("#add-num");
			var praise_txt = $("#praise-txt");
			var num=parseInt(praise_txt.text());
			if(praise_img.attr("src") == ("{% static 'img/likes1.png' %}")){
				$(this).html("<img src='{% static 'img/likes.png' %}' id='praise-img' class='animation' />");
				praise_txt.removeClass("hover");
				text_box.show().html("<em class='add-animation'>-1</em>");
				$(".add-animation").removeClass("hover");
				num -=1;
				praise_txt.text(num)
			}else{
				$(this).html("<img src='{% static 'img/likes1.png' %}' id='praise-img' class='animation' />");
				praise_txt.addClass("hover");
				text_box.show().html("<em class='add-animation'>+1</em>");
				$(".add-animation").addClass("hover");
				num +=1;
				praise_txt.text(num)
			}
		});
	})
</script>
<script>
    $(function(){
        $('#praise').click(function(){
            var praise_img = $("#praise-img");

            if(praise_img.attr("src") == ("{% static 'img/likes1.png' %}")){
                $.ajax({
                    type: "GET",
                    data: {"op":"add"},
                    url: "{% url 'like' article.pk %}",
                    cache: false,
                    dataType: "html"
                });
            }else{
                $.ajax({
                    type: "GET",
                    data: {"op":"sub"},
                    url: "{% url 'like' article.pk %}",
                    cache: false,
                    dataType: "html"
                });
            }
        });
    })
</script>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-ch">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-Type" content="text/html">
    <meta name="description" content="kiosk's blog">
    {% block title %}{% endblock %}
    <!-- Bootstrap Core CSS -->
    {% block css %}{% endblock %}
    <link href='{% static 'css/bootstrap-theme.css' %}' rel="stylesheet">
    <link href='{% static 'css/bootstrap.css' %}' rel="stylesheet">
    <link href='{% static 'css/common.css' %}' rel="stylesheet">
    {% block style %}{% endblock %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block js %}{% endblock %}
</head>

<body>
<!-- Navigation -->
<div id="container">
<header>
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" style="height: 70px" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <div style="margin-top:10px;font-size: xx-large;font-family: sans-serif" class="navbar-brand">kiosk 多彩世界</div>
                <button  style="margin-top: 30px" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
{#                    <span class="icon-bar"></span>#}
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right" style="margin-top: 0px">
                    <li><a class="base-nav" href="/"><span style="font-size: large" class="glyphicon glyphicon-home">blog首页</span></a></li>
                    <li><a class="base-nav" href="{% url 'index' %}"><span style="font-size: large" class="glyphicon glyphicon-list">博客</span></a></li>
{#                    <li><a class="base-nav" href="/"><span style="font-size: large" class="glyphicon glyphicon-fire">案例</span></a></li>#}
                    <li><a class="base-nav" href="http://blog.csdn.net/Ghost_leader"><span style="font-size: large" class="glyphicon glyphicon-question-sign">关于</span></a></li>
                    <li style="margin: 10px">
                        <form class="navbar-form navbar-left" role="search" action="/search/" method="get">
                            <div class="form-group">
                                <input type="text" name="search_for" class="form-control" placeholder="Search">
                            </div>
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <!-- Page Content -->
<section class="main">
    {% block content %}{% endblock content %}
</section>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 20px">
                <p style="text-align: center;">Copyright &copy; kiosk的博客 2018</p>
            </div>
            <!-- /.col-lg-12 -->
            <div class="col-lg-12" style="text-align: center;">
                <a href="https://github.com/weijiaxiang007">Github</a>
            </div>

        </div>
        <!-- /.row -->
    </footer>
</div>


</body>
</html>

templates/category.html
{% extends 'index.html' %}


{% block head %}博客分类：{{ category }}{% endblock %}

{% block panel_style %}<div class="panel panel-default panel-danger">{% endblock %}

templates/comment.html
{% load static %}

<div class="col-sm-10 col-md-10 col-lg-10 col-sm-offset-1 col-md-offset-1 col-lg-offset-1">
    <div class="panel panel-default panel-warning">
        <div class="panel-heading">
            <h3>评论区</h3>
        </div>
        <div class="panel-body">
            {% for comment in comment_list %}
                <ul class="media-list">
                    <li class="media comment">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object" src="{% static 'img/header.png' %}">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">{{ comment.user_name }}</h4>
                            {{ comment.body }}
                        </div>
                    </li>
                </ul>
            {% empty %}
                <div class="blog">
                    <h3></h3>
                </div>
            {% endfor %}
        </div>
    </div>

    <form id="comment_form" class="bootstrap-frm">
        {% csrf_token %}
        <h1>评论留言</h1>
        <label for="id_body">
            <textarea id="id_body" name="body" placeholder="Send Message To Me"></textarea>
        </label>
        <p style="margin-left: 30px" id="body_error"></p>
        <label for="id_user_name" class="input-group" style="width: 50%">
            <input id="id_user_name" type="text" class="form-control" placeholder="请输入姓名" aria-describedby="basic-addon2">
        </label>
        <span id="name_error"></span>
        <button class="button" type="submit" id="submit">提交</button>
    </form>
</div>

<script>
    $(document).ready(function(){
        $.ajaxSetup({
                 data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
            });
        $('#comment_form').submit(function(){
                var body = $("#id_body").val();                 //获得form中用户输入的name 注意这里的id_name 与你html中的id一致
                var user_name = $("#id_user_name").val();    //同上

                $.ajax({
                    type:"POST",
                    data: {body:body, user_name:user_name},
                    url: "{% url 'comment' article.pk %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致#}
                    cache: false,
                    dataType: "html",
                    success: function(result, statues, xml) {
                        if (result) {
                            var jsonData = JSON.parse(result);
                            $("#body_error").html(jsonData['body_error']);
                            $("#name_error").html(jsonData['username_error'])
                        }else{
                            $("#id_body").val("Send Message To Me");
                            $('#id_user_name').val('请输入名字')
                            window.location.reload()   //提交表单后强行刷新页面
                        }
                    },
                    error: function(result){
                        alert(result);
                    }
                });
                return false;
            });

        });
</script>

templates/date_list.html
{% extends 'index.html' %}

{% block head %}日期归档：{{ date }}{% endblock %}

{% block panel_style %}<div class="panel panel-default panel-success">{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>kiosk的博客</title>
{% endblock %}

{% block style %}
    <link href='{% static 'css/soul.css' %}' rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'js/lottie.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
                <div id="bm"></div>
            </div>
            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7" style="margin-top: 100px">
                <figure class="l-col-left soul-wrap" role="img" aria-label="Currently, the web is all system, no soul. (Jason Pamental)">
                    <div class="soul" aria-hidden="true">
                        <span class="soul__ldquo">“</span>
                        <span class="soul__currentl">Welcome</span>
                        <span class="soul__y">&nbsp;To</span>
                        <span class="soul__web">my website</span>
                        <span class="soul__is">
                            <span>is</span>
                        </span>
                        <span class="soul__all">
                            <span>A<span zw> </span>L<span zw> </span>L</span>
                        </span>
                        <span class="soul__system">
                        <span>S<span zw> </span>Y<span zw> </span>S<span zw> </span>T<span zw>
                        </span>E<span zw> </span>M</span></span>
                        <span class="soul__no-soul"><span>no</span> <span>soul</span></span>
                        <span class="soul__rdquo">„</span>
                        <span class="soul__jason">- John Kiosk</span>
                    </div>
                </figure>
            </div>
        </div>
    </div>
    <script>
        var animation = bodymovin.loadAnimation({
            container: document.getElementById('bm'),
            renderer: 'svg',
            loop: true,
            autoplay: true,
            path: '{% static 'data.json' %}'
        });


        animation.playSegments([[0,39],[40,206]],true);
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <style>
        body{
            background-image: url("{% static 'img/fire.jpg' %}");
            background-repeat:no-repeat;
            background-attachment:fixed;
            background-position:center;
        }
    </style>
{% endblock %}

{% block title %}
    <title>kiosk的博客</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-sm-11 col-md-11 col-lg-11">
            <div class="jumbotron  head-type">
                <div class="container">
                <h2 class="head-font">Kiosk</h2>
                <p class="head-font">kiosk make kiosk everywhere | Kiosk的目标是到处都是kiosk，嗯！</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                {% block panel_style %}<div class="panel panel-default panel-warning">{% endblock %}
                <div class="panel-heading">
                    <h3>{%  block head%}我的博客{% endblock %}</h3>
                </div>
                <div class="panel-body">
                    <blockquote class="blockquote-reverse">
                        {#       取分页器中的变量以获得所有的文章数量       #}
                        <small>一共有{{ article_list.paginator.count }}篇博客 </small>
                    </blockquote>
                    {% for article in article_list %}
                        <div class="blog">
                            <h3><a href="{% url 'article' article.pk %}">{{ article.title }}</a></h3>
                            <p class="blog-info">
                                <span class="glyphicon glyphicon-folder-open blog-label">：{{ article.category }}</span>
                                <span class="glyphicon glyphicon-time blog-label">：{{ article.created_time|date:'Y-m-d' }}</span>
                            </p>
                            <p>{{ article.content | truncatechars:120|striptags }}</p>
                            <p class="blog-info-header">
                                <span class="glyphicon glyphicon-thumbs-up blog-info-footer-1">：{{ article.likes }}</span>
                                <span class="glyphicon glyphicon-eye-open blog-info-footer-2">：{{ article.views }}</span>
                            </p>
                        </div>
                    {% empty %}
                        <div class="blog">
                            <h3>--- 暂无博客，敬请期待 ---</h3>
                        </div>
                    {% endfor %}

                </div>
                </div>
            </div>
            <div class="hidden-xs hidden-sm col-md-4 col-lg-4">
                {% if index == 'yes' %}
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong class="head-font">Kiosk's</strong>
                    </div>
                    <div class="panel-body">
                        <p>用<b>Python</b>郑重地写下一行“Hello World”<p>
                        <p style="text-align: center"><img src="{% static 'img/GitHub.png' %}"><span style="margin-left: 20px"><a href="https://github.com/weijiaxiang007">Weijiaxiang007@Github</a></span></p>
                    </div>
                </div>
                {% endif %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        博客分类
                    </div>
                    <div class="panel-body">
                        <ul class="blog-types">
                            {% for category in category_list %}
                                <li><a href="{% url 'category' category.id %}">{{ category.category }} <span class="badge">{{ category.count }}</span></a></li>
                            {% empty %}
                                <li>暂无分类</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        日期归档
                    </div>
                    <div class="panel-body">
                       <ul class="blog-types">
                           {% for blog_date in date_list %}
                               <li><a href="{% url 'date' blog_date.year blog_date.month %}">
                                   {{ blog_date|date:'Y年m月' }}
                               </a></li>
                           {% endfor %}
                       </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <nav style="text-align: center" aria-label="Page navigation">
                <ul class="pagination pagination-lg">
                    <li>
                        {% if article_list.has_previous %}
                            {% if search %}
                                <a href="?search_for={{ search_for }}&amp;page={{ article_list.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% else %}
                                <a href="?page={{ article_list.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            {% endif %}
                        {% else %}
                            <span aria-hidden="true">&laquo;</span>
                        {% endif %}
                    </li>
                    {% for page_num in page_range %}
                        {% if page_num == article_list.number %}
                            <li class="active"><span>{{ page_num }}</span></li>
                        {% else %}
                            {% if page_num == '...' %}
                                <li><span>{{ page_num }}</span></li>
                            {% else %}
                                {% if search %}
                                    <li><a href="?search_for={{ search_for }}&amp;page={{ page_num }}">{{ page_num }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page_num }}">{{ page_num }}</a></li>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    <li>
                        {% if article_list.has_next %}
                            <a href="?page={{ article_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        {% else %}
                            <span aria-hidden="true">&raquo;</span>
                        {% endif %}
                    </li>
                </ul>
                <p style="font-size: 12px;color: white">当前是{{ article_list.number }}页,共有{{ last_page }}页</p>
            </nav>
        </div>
    </div>
{% endblock %}

templates/search.html
{% extends 'index.html' %}

{% block head %}查找结果：{{ date }}{% endblock %}

{% block panel_style %}<div class="panel panel-default panel-success">{% endblock %}